version: '3'

services: 
  delivery_service:
    container_name: delivery_service
    build: ./Services/DeliveryService/.
    ports:
      - 8000:80
    environment:
      - POSTGRES_URL=postgresql+psycopg2://admin:admin@localhost:5432/DeliveryService_db
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
  
  notification_service:
    container_name: notification_service
    build: ./Services/NotificationService/.
    ports:
      - 8002:80
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
