"""init

Revision ID: 100c2bc8c77b
Revises: 
Create Date: 2024-03-21 00:36:36.979173

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100c2bc8c77b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        deliverystatuses_enum = postgresql.ENUM('ACTIVATE', 'DONE', name='deliverystatuses')
        deliverystatuses_enum.create(op.get_bind(), checkfirst=True)
    except sa.exc.ProgrammingError as e:
        if 'already exists' in str(e):
            # Type already exists, do nothing
            pass
        else:
            raise e
    op.create_table('delivery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', deliverystatuses_enum, nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###\
    deliverystatuses_enum = postgresql.ENUM('ACTIVATE', 'DONE', name='deliverystatuses')
    deliverystatuses_enum.drop(op.get_bind())
    op.drop_table('delivery')
    # ### end Alembic commands ###
